version: 0
index_id: hdfs_logs
index_uri: s3://path-to-your-bucket/hdfs_logs

doc_mapping:
  field_mappings:
  - name: timestamp
    type: i64
    fast: true
  - name: severity_text
    type: text
    tokenizer: raw
  - name: body
    type: text
    tokenizer: default
    record: position
  - name: resource
    type: object
    field_mappings:
    - name: service 
      type: text
      tokenizer: raw
  - name: attributes
    type: object
    field_mappings:
    - name: class
      type: text
      tokenizer: raw
  tag_fields: []

indexing_settings:
  store_source: false
  timestamp_field: timestamp
  resources:
    heap_size: 50MB
    
search_settings:
  default_search_fields:
  - body
  - severity_text
