version: 0
node_id: searcher-2
metastore_uri: s3://path/to/bucket/indexes # change this to your S3 bucket
default_index_root_uri: s3://path/to/bucket/indexes # change this to your S3 bucket
searcher:
  rest_listen_address: 127.0.0.1
  rest_listen_port: 7290
  peer_seeds:
    - 127.0.0.1:7280 # searcher-1
    - 127.0.0.1:7300 # searcher-3
