[package]
name = "quickwit-telemetry"
description = "Open Telemetry services"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
async-trait = { workspace = true }
hostname = { workspace = true }
md5 = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
username = { workspace = true }
uuid = { workspace = true }

# This is actually not used directly the goal is to fix the version
# used by reqwest. 0.8.30 has an unclear license.
encoding_rs = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
