[package]
name = "quickwit-directories"
description = "Custom `tantivy::Directory` implementations for Quickwit"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
tantivy = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

quickwit-common = { workspace = true }
quickwit-storage = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
