[package]
name = "quickwit-doc-mapping"
version = "0.1.0"
authors = ["Quickwit, Inc. <hello@quickwit.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
tantivy = "0.14"
serde_json = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
