#
# Index config file for receiving logs in OpenTelemetry format.
# Link: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md
#

version: 0

index_id: otel-trace

doc_mapping:
  mode: lenient # TODO: change to strict eventually
  field_mappings:
    - name: trace_id
      type: text
      tokenizer: raw
    - name: span_id
      type: text
      tokenizer: raw
    - name: trace_state
      type: text
      tokenizer: raw
    - name: parent_span_id
      type: text
      tokenizer: raw
    - name: name
      type: text
      tokenizer: raw
    - name: kind
      type: json
    - name: service_name
      type: text
      tokenizer: raw
    - name: start_timestamp_nanos
      type: datetime
      input_formats:
        - unix_ts_micros # TODO: change to unix_ts_nanos
      fast: true
      precision: seconds
    - name: end_timestamp_nanos
      type: datetime
      input_formats:
        - unix_ts_micros # TODO: change to unix_ts_nanos
      fast: true
      precision: seconds
    - name: attributes
      type: json
    - name: dropped_attributes_count
      type: u64
    # - name: events
    - name: dropped_events_count
      type: u64
    # - name: links
    - name: dropped_links_count
      type: u64
    - name: status
      type: json

indexing_settings:
  commit_timeout_secs: 5
  timestamp_field: start_timestamp_nanos

search_settings:
  default_search_fields: []

