[package]
name = "quickwit-metastore-utils"
description = "Metastore utilities"

version.workspace = true
edition.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "replay"

[[bin]]
name = "proxy"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
quickwit-proto = { workspace = true }
serde = "1"
serde_json = { workspace = true }
structopt = "0.3"
tokio = { workspace = true }
