on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "quickwit-*/**"

name: CI

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1

jobs:
  ci-passes:
    name: CI passes
    runs-on: ubuntu-latest
    container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
    needs:
      - clippy
      - fmt
      - test
    steps:
      - run: exit 0

  license-check:
    name: License-check
    runs-on: ubuntu-latest
    container: public.ecr.aws/l6o9a3f9/apache-skywalking-eyes:latest
    steps:
        - uses: actions/checkout@v2
        - run: /bin/license-eye -v debug

  clippy:
    name: Lint
    runs-on: ubuntu-latest
    container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --workspace --tests
      - uses: actions-rs/cargo@v1
        name: cargo deny
        with:
          command: deny
          args: check License

  fmt:
    name: Check format
    runs-on: ubuntu-latest
    container: public.ecr.aws/l6o9a3f9/quickwit-builder:latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo fmt --all -- --check

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup localstack
        run: docker-compose -f localstack.yaml up -d
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Create bucket in localstack
        run: docker-compose -f localstack.yaml exec -T localstack awslocal s3 mb s3://quickwit-integration-tests
      - name: Run all tests.
        env:
          AWS_ACCESS_KEY_ID: dummy-access-key
          AWS_SECRET_ACCESS_KEY: dummy-secret-key
        run: cargo test --all-features
