[build.env]
passthrough = [
    "QW_COMMIT_DATE",
    "QW_COMMIT_HASH",
    "QW_COMMIT_TAGS",
]

[target.x86_64-unknown-linux-gnu]
image = "quickwit/cross:x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "quickwit/cross:x86_64-unknown-linux-musl"
RUSTFLAGS="LIB_LDFLAGS=-L/usr/lib/x86_64-linux-gnu CFLAGS=-I/usr/local/musl/include CC=musl-gcc"

[target.aarch64-unknown-linux-gnu]
image = "quickwit/cross:aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-musl]
image = "quickwit/cross:aarch64-unknown-linux-musl"
linker = "aarch64-linux-musl-gcc"

[target.aarch64-unknown-linux-musl.env]
# Fix build for transitive dependency rdkafka -> rdkafka-sys -> sasl2-sys -> krb5-src
passthrough = ["KRB5_CV_ATTR_CONSTRUCTOR_DESTRUCTOR=yes", "AC_CV_FUNC_REGCOMP=yes", "AC_CV_PRINTF_POSITIONAL=yes"]
